//
//  Container.swift
//  
//
//  Created by Ana Elisa Lima on 09/02/24.
//

import Foundation

class Container {
    static let elements: [Call] = [
        Call(id: 1,
             navigationTitle: "Valentina Tereshkova",
             scientistImage: "ValentinaTereshkova",
             education: "Graduated from Light Industry Technical School in 1960 by taking correspondence courses. Later graduated from Zhukovky Air Force Academy as a professional engineer on October 1969 and earned a doctorate in aeronautical engineering in 1977.",
             biography: "Valentina Vladimirovna Tereshkova was born on March 6th, 1937 in the village of Bolshoye Maslennikovo, Yaroslavl Oblast (central Russia). After her father's death in 1939, she moved with her family to Yaroslavl. Valentina was first enrolled in school at the age 10 and graduated at 17. She began working at a tire factory, and later at a textile mill, but continued her education by taking correspondence courses and graduated in 1960. She also became interested from a young age in parachuting, making her first jump at age 22, on May 21, 1959. While still employed as a textile worker, she trained as a competitive parachutist, keeping this a secret from her family.\nValentina was select as a cosmonaut in February 1962, along with other four women, making them the first female cosmonauts. She flew on Vostok 6 in June 16, 1963, becoming the first woman to go to space. She conducted medical studies on humans in spaceflight and offered comparative data about the effects of space travel on women, and spent 22 hours, and 50 minutes in space. As the mission was coming to an end, she ejected from the capsule during its descent at about four miles above the Earth and made a parachute landing 620 km north-east of Karaganda, Kazakhstan.\nAfter her flight, she became a national and international role model. She graduated as a professional engineer and later earned her doctorate in aeronautical engineering. She never came back to space again but remained as an instructor at the Yuri Gagarin Cosmonaut Training Center and later became active in political life.\nValentina Tereshkova is still considerated an inspiration for young girls and women around the world for her pioneering and perseverance.",
             endingImage:"ValentinaTereshkova2",
             subtitle:"Valentina Tereshkova posing with Vostok 6"),
        
        Call(id: 2, 
             navigationTitle: "Sally Ride",
             scientistImage: "SallyRide",
             education: "B.S in Physics and B.A in English Literature (1973); M.S (1975) and PhD (1978) in Physics from Stanford University.",
             biography: "Sally Kristen Ride was born on May 26, 1951 in Los Angeles, California (USA). In 1960, when she was nine years old, her family spent a year traveling in Europe. In Spain, she played tennis for the first time and really enjoyed it. At age 10, Sally was coached by Alice Marble, a former world number one player, and by 1963 she was ranked number 20 in Southern California for girls aged 12 and under. Although she was building a career in tennis, she wanted to be an astrophysicist, and took advanced math classes on summer break after graduating from high school in 1968.\nSally firstly joined Swarthmore College but after three semesters she entered the University of California, Los Angeles (UCLA) and later transferred to Stanford University as a junior. During the meantime, she played on many tennis matches and even considerated to be a professional tennis player but later decided to follow a career as a scientist, buiding an academic background in Physics.\nIn January of 1977, Sally spotted an article on the front page of The Stanford Daily that told how NASA was recruiting a new group of astronauts for the Space Shuttle program and wanted to recruit women. She was selected out of 8,079 applications NASA received by June 1977 and became one of the six women selected to be the first American female astronauts in 1978. She completed her training by August 1979 and became a full-fledged astronaut. She flew on STS-7 on June 18, 1983 becoming the first American female astronaut and the third woman overall. The purpose of the mission was to deploy two communications satellites: one for Canada and another for Indonesia. Sally operated the robot arm which she early worked on. The mission lasted 6 days, 2 hours, 23 minutes and 59 seconds.\nShe later flew on STS-41-G on October 13, 1984. She was also scheduled to fly on STS-61-M in July 1986 but due to the Space Shuttle Challenger disaster that took place on January 1986 the flight was cancelled, and Sally never came back to space again. She left NASA in 1987 and became a professor of Physics at the University of California, San Diego (UCSD) in 1989. She remained there until 2007.\nSally Ride died on July 23, 2012 at the age of 61 by a pancreatic cancer. Until today, she is considered an American heroe and an inspiration for people, and especially women around the world.",
             endingImage: "SallyRide2",
             subtitle: "Sally Ride and the crew of STS-7"),
        
        Call(id: 3,
             navigationTitle: "Mae Jemison",
             scientistImage: "MaeJemison",
             education: "B.S in Chemical Engineering and B.A in African and African-American studies (1977) from Stanford University; M.D degree (1981) from Cornell University.",
             biography: "Mae Carol Jemison was born on October 17, 1956 in Decatur, Alabama (USA). From a young age, she knew that she wanted to study science and someday go into space. She started ballet at the age of 8 or 9 and entered high school by the age of 12. She was part of the cheerleading team and the Modern Dance Club. From a young age, Mae also had a great passion for dance and learned several styles of dance, including African and Japanese, as well as ballet, jazz, and modern dance, and she even participated on a school musical as a background dancer.\nMae graduated from high school in 1973 and joined Stanford University at the age of 16. There were very few other African-American students in her classes and she experienced discrimination from her teachers. At university, she served as head of the Black Students Union and also choreographed a musical and dance production called 'Out of the Shadows'. She also pursued studies related to her childhood interest in space and first considered applying to NASA. During her junior year, she struggled with the choice between going to medical school or pursuing a career as a professional dancer after graduation. She chose the former and after graduating from Stanford in 1977 she joined Cornell Medical School.\nAt Cornell, Mae conduct a study funded by American Medical Student Association in Cuba and worked on a Cambodian refugee camp in Thailand. She also took dance lessons at Alvin Ailey American Dance Theater. After graduating, she interned at Los Angeles County-USC Medical Center in 1982 and joined the Peace Corps in 1983, where she served in Liberia and Sierra Leone.\nMae firstly applied to be an astronaut in October 1985 but due to the Space Shuttle Challenger Disaster, NASA postponed selection, and she reapplied in 1987. She was select out of a pool of 2,000 applications. She flew on STS-47 on September 12, 1992 and logged 190 hours, 30 minutes, 23 seconds in space. With this being her only flight, she became the first Afro-American to go to space. Mae resigned from NASA in March 1993 to start a company called The Jemison Group Inc. Since that, she worked on scientific organizations, wrote books and participated in many events, shows, programs and talks.\nMae Jemison continues to be an inspiration for her perseverance and courage to follow her dreams and break discrimination.",
             endingImage: "MaeJemison2",
             subtitle: "Mae Jemison and the crew of STS-47"),
        
        Call(id: 4,
             navigationTitle: "Ellen Ochoa",
             scientistImage: "EllenOchoa",
             education: "B.S in Physics (1980) from San Diego State University; M.S (1981) and PhD (1985) in Electrical Engineering from Stanford University.",
             biography: "Ellen Lauri Ochoa was born on May 10, 1958 in Los Angeles, California (USA) but grew up in La Mesa, California. Her paternal grandparents emigrated from Mexico to Arizona and later to California. Neither of her parents had college degrees but strongly encouraged her education. Ellen graduated from high school in 1975 as a top class student. She was accepted with a scholarship at Stanford University but declined the offer so that she could stay close and take care of her mother. At the time, her parents had just divorced and she decided to choose a college near by to help her family out.\nEllen joined San Diego State University initially with an interest in study music as she was a gifted musician (a flutist). However, as she got exposed into different classes, she found out that she loved physics, math, and engineering. Ultimately, she decided to major in Physics, and graduated Phi Beta Kappa in 1980. During her graduate studies, at Stanford Univeristy, she became fascinated by the field of optics and investigated optical systems for performing information processing. While a graduate student, she also worked at Sandia National Laboratory where she applied what she knew about optics to the research being done on nuclear weapons. She has presented numerous papers at technical conferences and in scientific journals.\nUpon receiving her PhD, in 1985, Ellen applied for the NASA Astronaut program for the first time, which was considered during the 1987 selection process, but wasn't select. She kept trying, and even got a pilot's licence. Finally, she was select in 1990 and became a full-fledged astronaut in 1991. She first flew on STS-56 on April 8, 1993 and became the first female astronaut of Hispanic descent to go to space. She spent nine days on space and conducted research on Earth's ozone layer. After this first flight, she flew on more three missions: STS-66 (November 3, 1994), STS-96 (June 6, 1999), and STS-110 (April 8, 2002).\nEllen Ochoa retired from spacecraft operations in 2007, and served as Deputy Director of NASA's Johnson Space Center. She also became the first Hispanic and second female director of the Johnson Space Center in 2013. To this day, Ellen continues to be an inspiring for hispanic/latina women.",
             endingImage: "EllenOchoa2",
             subtitle: "Ellen Ochoa and the crew of STS-56"),
        
        Call(id: 5,
             navigationTitle: "Chiaki Mukai",
             scientistImage: "ChiakiMukai",
             education: "M.D in Medicine (1977) from Keio University School of Medicine; PhD in Physiology (1988) from Keio University",
             biography: "Chiaki Mukai was born on May 6, 1952 in Tatebayashi, Gunma Prefecture (Japan). She graduated from high school in 1971, and earned her doctor of medicine (M.D) in 1977. She received her PhD in Physiology in 1988 and a board certified as a cardiovascular surgeon from Japan Surgical Society in 1989. During her career, Chiaki has held positions at several hospitals and institutions across Japan since 1977 such as resident, medical staff, chief resident, and assistant professor. She has also been credited with approximately sixty peer-reviewed scientific publications since 1979.\nIn August of 1985, Chiaki was selected by the National Space Development Agency of Japan (NASDA, currently Japan Aerospace Exploration Agency) as one of three Japanese Payload Specialist candidates for the First Material Processing Test (Spacelab-J) mission. Between 1987 and 1988, she was a visiting scientist of the Division of Cardiovascular Physiology, Space Biomedical Research Institute, NASA Johnson Space Center. She first flew on STS-65 on July 8, 1994, and worked on experiments related to the cardiovascular and autonomic nerve system, as well as bone and muscle metabolism. She became the first Japanese woman in space, the first Japanese citizen to have two spaceflights, and the first Asian woman in space. She spent 14 days, 17 hours, 55 minutes in space.\nChiaki second and last flight happened on October 29, 1998 on STS-95. The crew contributed to the deployment of the Hubble Space Telescope Orbital Systems Test Platform and the Spartan spacecraft, which was used for studying solar wind. She spent 9 days, 19 hours, 54 minutes, 2 seconds in this mission. In total, she logged 23 days, 15 hours, and 39 minutes in space.\nChiaki Mukai is still part of Japan Aerospace Exploration Agency (or JAXA) where she served as director of the Space Biomedical Research Office, Human Space Technology and Astronaut Department, Human Space System and Utilization Mission Directorate. She is currently a Senior Advisor to the Executive Director of JAXA and Vice President of the Tokyo University of Science. To this day, she continues to be an inspiration for her pioneering, courage and success.",
             endingImage: "ChiakiMukai2",
             subtitle: "Chiaki Mukai and the crew of STS-65"),
        
        Call(id: 6,
             navigationTitle: "Eileen Collins",
             scientistImage: "EileenCollins",
             education: "A.A in Mathematics (1976) from Corning Community College; B.A in Mathematics and Economics (1978) from Syracuse University; M.S in Operations Research (1986) from Stanford Univeristy; M.A in Space Systems Management (1989) from Webster University.",
             biography: "Eileen Marie Collins was born on November 19, 1956 in Elmira, New York (USA). As a child, she was shy and needed speech therapy for her stutter. She expressed an early interest in becoming a pilot, subscribing to Air Force Magazine and reading books about aviators. After graduating from high school, in 1974, she considered join the US Air Force but her father was adamantly opposed. Eileen then attended Corning Community College where she earned an associate degree in Mathematics in 1976. She then entered Syracuse University, which she chose because it had an Air Force Reserve Officer Training Corps (AFROTC) program.\nIn 1975, the United States Air Force (USAF) changed its policy to allow women to train as pilots, although only for non-combat missions. After graduating from college, in 1978, Eileen began her basic training and later applied for pilot training. Before joining the Undergraduate Pilot Training (UPT) program, she participated in Flight Screening Program (FSP) which purpose was to screen out unsuitable pilots before sending them to UPT. She was almost eliminated due to her eye sight but later was accepted. By March 1979, she received her pilot wings and was assigned as a flight instructor.\nAfter some years as a flight instructor, Eileen set her mind to become an astronaut. Her first step was USAF Test Pilot School. Through experience as a transport aircraft pilot, service in the American Invasion of Grenada, teaching as an assistant professor in Mathematics at the United States Air Force Academy, and earning two Master's degrees, she was accepted into USAF Test Pilot School in 1989. She became the second woman pilot to attend it when she joined and graduated in June 1990.\nEileen was selected as an astronaut in January 1990 and reported for duty after graduting from USAF Test Pilot School. She trained as a pilot and became a full-fledged astronaut a year later. She first flew on STS-63 on February 3, 1995, and became the first female pilot astronaut. She spent 8 days, 6 hours, 28 minutes, 15 seconds in space. She later flew on more three missions: STS-84 (May 15, 1997), STS-93 (July 23, 1999), where she served as commander of the mission becoming the first female commander of the space shuttle program, and STS-114 (July 26, 2005), the first flight after the Space Shuttle Columbia Disaster in 2003. She logged 36 days, 7 hours, and 11 minutes in space.\nEileen Collins retired from the U.S. Air Force in January 2005. She leaved NASA by May 2006 to spend more time with her family and pursue other interests. She received many awards and honors for her service and pioneering and until now she is one of the only three women who pilot the space shuttle.",
             endingImage: "EileenCollins2",
             subtitle: "Eileen Collins and the crew of STS-63"),
        
        Call(id: 7,
             navigationTitle: "Kalpana Chawla",
             scientistImage: "KalpanaChawla",
             education: "B.E in Aeronautical Engineering (Punjab Engineering College, India), 1982; M.S in Aerospace Engineering (University of Texas at Arlington), 1984; M.S in Mechanical Engineering (1986) and PhD in Aerospace Engineering (1988) from University of Colorado Boulder.",
             biography: "Kalpana Chawla was born on March 17, 1962 in Karnal (Haryana, India) but her parents later changed her birth date to July 1, 1961 so she could join school. As a little girl, she used to attend air flying clubs with her father and brother. Until she started school, she hadn't been formally named. Her parents called her Montu, but she picked her own name Kalpana meaning 'idea' or 'imagination'. Her passion for aviation led her to study engineering, an uncommon career for women at the time. At 20, after graduating from Punjab Engineering College in Aeronautical Engineering, Kalpana moved to the US to pursue graduate studies.\nIn 1988, after completing her PhD in Aerospace Engineering, she began her career at NASA Ames Research Center, where she did computational research about aircraft take-off and landing concepts (V/STOL). In 1993, she joined Overset Methods, Inc. as vice president and Research Scientist specializing in simulation of moving multiple body problems. In 1994, she was selected for NASA's Astronaut Group 15 and graduated a year later, in 1995, as a Mission Specialist.\nOn November 19, 1997, she flew into space for the first time, as Mission Specialist 1, on STS-87 and became the first woman of Indian descent to go to space.\nUpon 1998, NASA invited Kalpana's secondary school to take part in their Summer Space Experience Program. Each year, the school sent two girls to the Foundation for International Space Education's United Space School in Houston, Texas (USA) and Kalpana would invite them into her home for an Indian dinner. She knew about the necessity of providing science education opportunities for young girls in India and used her position as astronaut to fight for this cause.\nIn 2000, she was selected for STS-107, as Mission Specialist 2, which flew on February 16, 2003. The 16-day mission would end with a fateful accident: during re-entry, the shuttle exploded. All seven astronauts died.\nToday, even twenty one years after the accident, Kalpana still remains as an inspiration to people around the globe: a woman who broke barriers and changed the world with her perseverance and courage.",
             endingImage: "KalpanaChawla2",
             subtitle: "Kalpana Chawla and the crew of STS-107"),
        
        Call(id: 8,
             navigationTitle: "Liu Yang",
             scientistImage: "LiuYang",
             education: "PLA Air Force Aviation University, China (2001); PhD in Sociology (Tsinghua University, China).",
             biography: "Liu Yang was born on October 6, 1978 in Zhengzhou, Henan (China). Growing up, she never dreamt of becoming a taikonaut. She inspired to be a lawyer as the characters she saw on TV, or a bus conductor as there were few buses on the town she grew up. However, on her senior year of high school, PLA Air Force (Chinese Air Force) was recruiting female pilots in her hometown, and she decided to apply. She joined the team of the seventh group of female pilots in China in 1997, and qualified as a pilot before becoming the deputy head of a flight unit, holding the PLAAF rank of major. In the summer of 2001, after graduating from PLA Air Force Aviation University, she became a transport pilot for a division of the Guangkong Air Corps. She is a veteran pilot with 1,680 hours of flying experience.\nIn 2009, PLAAC (Chinese Astronaut Corps) was recruting the second group of Chinese taikonauts. Women were encouraged to apply, although they had two special requirements: be married and be a mother. Liu was already married but didn't have children. On the selection process for the taikonaut corps, however, she wasn't alone as five out of the other six women candidates also weren't mothers. In 2010, together with five newly selected astronauts, she entered the Chinese Astronaut Center. After two years of training, she joined the selection process for Shenzhou 9 mission, and in 2012 became part of the crew along with other two male taikonauts.\nLiu first flew on June 16, 2012 aboard Shenzhou 9 spacecraft, and was on the first crewed mission and expedition to dock with the Tiangong-1 space station. The mission was launched exactly 49 years after the pioneer flight of Valentina Tereshkova, the first female astronaut. Liu became the first Chinese woman in space, and performed experiments in space medicine on her first mission. She was launched again aboard Shenzhou 14 on June 5, 2022. The mission lasted six months, during which she assisted with the Tiangong space station's assembly and expansion. She also became the first Chinese woman to do a spacewalk. She has logged 195 days, 0 hours, and 50 minutes in space.\nLiu Yang aspirations are to continue to be a taikonaut and keep working on Tiangong space station. In her interviews, she always stated that men and women don't have differences when it comes to space. She also stated that although she was the first female Chinese in space, she never was treated differently on her training. She is an inspiration for women around China and the world for her pioneering and hard-working.",
             endingImage: "LiuYang2",
             subtitle: "Liu Yang and the crew of Shenzhou 9"),
        
        Call(id: 9,
             navigationTitle: "Samantha Cristoforetti",
             scientistImage: "SamanthaCristoforetti",
             education: "B.E and M.S in Mechanical Engineering (Technical University of Munich, Germany), 2001; B.S in Aeronautical Sciences (University of Naples Federico II, Italy), 2005.",
             biography: "Samantha Cristoforetti was born on April 26, 1977 in Milan (Italy). She spent her childhood in Malè (Italy). She completed her secondary education at the Liceo Scientifico in Trento (Italy), in 1996, after having spent one year as an exchange student in the USA. She also attended Space Camp on her time there. She graduated from the Technical University of Munich with specialisations in aerospace propulsion and lightweight structures. As part of her studies, she spent four months at the Ecole Nationale Supérieure de l’Aéronautique et de l’Espace in Toulouse (France) working on an experimental project in aerodynamics. She wrote her master’s thesis in solid rocket propellants during a 10-month research stay at the Mendeleev University of Chemical Technologies in Moscow (Russia).\nSamantha joined the Italian Air Force in 2001 and was admitted to the Air Force Academy as an officer candidate. As part of her training at the institution, she also completed a bachelor’s degree in aeronautical sciences at the University of Naples Federico II. In 2005, after graduating, she attended the Euro-NATO Joint Jet Pilot Training program at Sheppard Air Force Base (USA), where she earned her fighter pilot wings in 2006. She became one of the first women to be a lieutenant and fighter pilot in the Italian Air Force. Upon her returning to Italy, she was assigned to fly the AM-X ground attack fighter at the 51st Bomber Wing in Istrana. In total, she has logged over 500 hours and has flown six different types of military aircraft.\nSamantha joined ESA as an astronaut candidate in May 2009, from a pool of 8,000 applicants. She completed her basic astronaut training in November 2010 and became a full-fledged astronaut. She first flew on Soyuz TMA-15M (Expedition 42/43) on November 23, 2014. She stayed 199 days at the International Space Station (ISS) and holded the record for the longest single mission for a woman until 2017. She also became the first Italian female astronaut in space. During the mission, she performed numerous scientific experiments simulating prolonged stays in space and Lunar and Mars orbit. Her second flight occured on April 27, 2022 as part of SpaceX Crew-4 mission. She was named the commander and spent 170 days on ISS. She also carried out the first spacewalk conducted by a European woman. In total, she has logged 370 days, 5 hours, 45 minutes in space.\nSamantha Cristoforetti is a UNICEF ambassador and donates to UNICEF the proceeds from sales of her memoir Diary of an Apprentice Astronaut, in which she shares her experience of being selected as an astronaut. She speaks six languages (Italian, English, German, French, Russian, and Chinese) and is an inspiration for women around the world.",
             endingImage: "SamanthaCristoforetti2",
             subtitle: "Samantha Cristoforetti and the crew of Soyuz TMA-15M"),
        
        Call(id: 10,
             navigationTitle: "Christina Koch",
             scientistImage: "ChristinaKoch",
             education: "B.S in Physics and Electrical Engineering (North Carolina State University), 2001; M.S in Electrical Engineering (North Carolina State University), 2002.",
             biography: "Christina Koch was born on January 29, 1979 in Grand Rapids, Michigan (USA) but was raised in Jacksonville, North Carolina (USA). As a child, she used to dream of becoming an astronaut. She graduated from high school in 1997 and then enrolled at North Carolina State University where she got both her bachelor's and master's degrees. During the latter she studied abroad at the University of Ghana (Ghana). In 2001, she became a graduate of the NASA Academy program at the Goddard Space Flight Center, where she contributed to instruments on several NASA space science missions.\nBetween 2004 and 2007, Christina worked as a Research Associate in the United States Antarctic Program, spending three-and-a-half years traveling the Arctic and Antarctic regions. She completed a winter-over season at the Amundsen–Scott South Pole Station where she experienced minus-111 degree Fahrenheit (-79.4 C) temperatures. She also served a season at Palmer Station. While in this role, she served as a member of the Firefighting and Search and Rescue Teams. Between 2007 and 2009, she worked as an electrical engineer in the Space Department of the Applied Physics Laboratory at Johns Hopkins University (USA) focusing on space science instrument development, such as Juno and the Van Allen Probes. She has also worked at some remote scientific bases. Throughout her career, she has done technical instructing, volunteer tutoring and educational outreach.\nChristina was select as an astronaut candidate in 2013. She completed training in July 2015 and became a full-fledged astronaut. She first flew on Soyuz MS-12 (Expedition 59/60/61) on March 14, 2019. She broke the record as the longest single mission for a woman, spending 328 days in space, and was also part of the first all-female spacewalk along with crewmate Jessica Meir. Later after return to Earth, she was assigned as part of the NASA Artemis program. On April 3, 2023, she was announced as a mission specialist in the Artemis II crew, which plans to fly around the Moon in 2025, traveling 6,400 miles beyond the Moon's far side before returning to Earth. By doing that, she is going to be the first woman to flyby the Moon. The mission is planned to occur in September 2025.\nChristina Koch received an Honorary PhD from North Carolina State University in 2020. She is currently training for her upcoming mission, along with other three crewmates (Reid Wiseman, Victor Glover and Canadian astronaut Jeremy Hansen). Their flight is going to be pioneer and one of the first steps to arrive on Mars one day. Although Artemis II hasn't happened yet, she has become an inspiration for her pioneering along with the excitement to see the first woman to ever orbit the Moon.",
             endingImage: "ChristinaKoch2",
             subtitle: "Christina Koch and the crew of Artemis II"),
    ]
}
